model_name_or_path: meta-llama/Llama-3.1-8B-Instruct

stage: sft
do_train: true
finetuning_type: full
resize_vocab: true

dataset_dir: LLaMA-Factory/data
dataset: anesqa_en
template: llama3
cutoff_len: 4096
# overwrite_cache: true
preprocessing_num_workers: 16

output_dir: outputs/llama3.1-8b-sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: true

per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
max_grad_norm: 5.0

per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

# accelerate:
# use_unsloth: true
use_badam: false
badam_mode: layer
badam_switch_mode: ascending
badam_switch_interval: 50
badam_verbose: 2
deepspeed: configs/examples/deepspeed/ds_z3_config.json
flash_attn: fa2
enable_liger_kernel: True
