### model
model_name_or_path: Qwen/Qwen2.5-7B

### method
stage: pt
do_train: true
finetuning_type: full
# finetuning_type: lora
# lora_target: all

### dataset
dataset_dir: LLaMA-Factory/data
dataset: anescorpus_en
cutoff_len: 2048
# overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/qwen2.5-7b-cpt
logging_steps: 5
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false

# accelerate:
# use_unsloth: true
use_badam: false
badam_mode: layer
badam_switch_mode: ascending
badam_switch_interval: 50
badam_verbose: 2
deepspeed: configs/examples/deepspeed/ds_z1_config.json
flash_attn: fa2
enable_liger_kernel: True

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
